// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// get_features
NumericVector get_features(std::string rna_seq, CharacterVector Struct_seq);
RcppExport SEXP _InvenireSRNA_get_features(SEXP rna_seqSEXP, SEXP Struct_seqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type rna_seq(rna_seqSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type Struct_seq(Struct_seqSEXP);
    rcpp_result_gen = Rcpp::wrap(get_features(rna_seq, Struct_seq));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_InvenireSRNA_get_features", (DL_FUNC) &_InvenireSRNA_get_features, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_InvenireSRNA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
